"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import { format } from "date-fns";
import { AgentReportBody } from "@/components/ai/AgentReportBody";

// Renders a compiled Report. Report.content is the array of AIReport envelopes
// gathered by gatherAgentReports (newest first); each entry has summary, payload,
// agentType, createdAt.

const titleCase = (s) =>
  typeof s === "string" && s.length > 0 ? s.charAt(0).toUpperCase() + s.slice(1) : s;


function EnvelopeCard({ envelope, agentType, index }) {
  const p = envelope?.payload;
  return (
    <div className="bg-white p-6 rounded-lg shadow border border-gray-100">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-semibold">
          {titleCase(agentType)} Report #{index + 1}
        </h2>
        {envelope?.createdAt && (
          <p className="text-sm text-gray-500">
            {format(new Date(envelope.createdAt), "MMM d, yyyy")}
          </p>
        )}
      </div>
      {envelope?.summary && (
        <div className="bg-blue-50 p-4 rounded-lg mb-4">
          <h3 className="text-sm font-medium text-gray-700 mb-1">Summary</h3>
          <p className="text-gray-700">{envelope.summary}</p>
        </div>
      )}
      <AgentReportBody agentType={agentType} payload={p} />
    </div>
  );
}

export default function ReportViewPage() {
  const params = useParams();
  const [report, setReport] = useState(null);
  const [client, setClient] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const reportResponse = await fetch(`/api/clients/${params.id}/reports/${params.reportId}`);
        if (!reportResponse.ok) throw new Error("Failed to fetch report");
        const reportData = await reportResponse.json();
        setReport(reportData.report);

        const clientResponse = await fetch(`/api/clients/${params.id}`);
        if (!clientResponse.ok) throw new Error("Failed to fetch client information");
        const clientData = await clientResponse.json();
        setClient(clientData.client);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, [params.id, params.reportId]);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-red-500">{error}</div>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-gray-500">Report not found</div>
      </div>
    );
  }

  // Report.content is Array<AIReport>; bound for safety.
  const envelopes = Array.isArray(report.content) ? report.content : [];

  return (
    <div className="container mx-auto py-8 px-4">
      <div className="bg-white rounded-lg shadow-md p-6">
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">
              {titleCase(report.type)} Report
            </h1>
            <p className="text-gray-600 mt-1">
              Generated by {report.createdBy?.name ?? "Unknown Counselor"}
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => window.print()}
              className="px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 rounded-md transition-colors flex items-center gap-2"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M5 4v3H4a2 2 0 00-2 2v3a2 2 0 002 2h1v2a2 2 0 002 2h6a2 2 0 002-2v-2h1a2 2 0 002-2V9a2 2 0 00-2-2h-1V4a2 2 0 00-2-2H7a2 2 0 00-2 2zm8 0H7v3h6V4zm0 8H7v4h6v-4z"
                  clipRule="evenodd"
                />
              </svg>
              Print Report
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8 p-6 bg-gray-50 rounded-lg">
          <div className="space-y-1">
            <p className="text-sm font-medium text-gray-500">Client</p>
            <p className="text-lg font-semibold text-gray-900">
              {client?.name || "Unknown Client"}
            </p>
            <p className="text-sm text-gray-600">
              {client?.age || "N/A"} years old • {client?.gender || "N/A"}
            </p>
          </div>
          <div className="space-y-1">
            <p className="text-sm font-medium text-gray-500">Report Date</p>
            <p className="text-lg font-semibold text-gray-900">
              {format(new Date(report.createdAt), "PPP")}
            </p>
            <p className="text-sm text-gray-600">{format(new Date(report.createdAt), "p")}</p>
          </div>
          <div className="space-y-1">
            <p className="text-sm font-medium text-gray-500">Time Period</p>
            <p className="text-lg font-semibold text-gray-900">
              {format(new Date(report.startDate), "MMM d, yyyy")} -{" "}
              {format(new Date(report.endDate), "MMM d, yyyy")}
            </p>
            <p className="text-sm text-gray-600">
              {Math.round(
                (new Date(report.endDate) - new Date(report.startDate)) / (1000 * 60 * 60 * 24)
              )}{" "}
              days
            </p>
          </div>
          <div className="space-y-1">
            <p className="text-sm font-medium text-gray-500">Status</p>
            <p className="text-lg font-semibold text-gray-900 capitalize">{report.status}</p>
            <p className="text-sm text-gray-600">Total entries: {envelopes.length}</p>
          </div>
        </div>

        {envelopes.length === 0 ? (
          <p className="text-gray-500">
            No agent outputs were found for the selected date range.
          </p>
        ) : (
          <div className="space-y-6">
            {envelopes.map((env, i) => (
              <EnvelopeCard
                key={env._id ?? i}
                envelope={env}
                agentType={env.agentType ?? report.type}
                index={i}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
